name: Deploy Backend Prefeitura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - run: |
          docker build -t devnardi/back-prefeitura:latest .
          docker push devnardi/back-prefeitura:latest

      - run: |
          docker rm -f back-prefeitura || true
          docker pull devnardi/back-prefeitura:latest
          docker run -d \
            --name back-prefeitura \
            -p 4000:3000 \
            --user 1001:1001 \
            --read-only \
            --cap-drop ALL \
            --security-opt no-new-privileges \
            --env-file /opt/back-prefeitura/.env \
            devnardi/back-prefeitura:latest
